embedding_dim: 2560
attack_module: model.transformer.wte
formatting_tokens:
  answer_prefix: "<|im_start|>assistant\n"
  answer_suffix: "<|im_end|>"
  prompt_prefix: "<|im_start|>user\n"
  prompt_suffix: "<|im_end|>\n"
hf_name: stanford-crfm/BioMedLM
attn_implementation: null
load_in_8bit: false
load_in_4bit: false
