embedding_dim: 8192
attack_module: model.embed_tokens
formatting_tokens:
  answer_prefix: <|START_OF_TURN_TOKEN|><|CHATBOT_TOKEN|>
  answer_suffix: <|END_OF_TURN_TOKEN|>
  prompt_prefix: <|START_OF_TURN_TOKEN|><|USER_TOKEN|>
  prompt_suffix: <|END_OF_TURN_TOKEN|>
hf_name: CohereForAI/c4ai-command-r-v01
attn_implementation: eager
load_in_8bit: true
load_in_4bit: false
