embedding_dim: 5120
attack_module: model.embed_tokens
formatting_tokens:
  answer_prefix: ""
  answer_suffix: ""
  prompt_prefix: "[INST] "
  prompt_suffix: " [/INST]"
hf_name: OpenDFM/ChemDFM-13B-v1.0
attn_implementation: flash_attention_2
load_in_8bit: false
load_in_4bit: false
