embedding_dim: 4096
attack_module: model.tok_embeddings
formatting_tokens:
  answer_prefix: "<|im_start|>assistant\n"
  answer_suffix: "<|im_end|>"
  prompt_prefix: "<|im_start|>user\n"
  prompt_suffix: "<|im_end|>\n"
hf_name: AI4Chem/ChemLLM-7B-Chat
attn_implementation: flash_attention_2
load_in_8bit: false
load_in_4bit: false
