embedding_dim: 7168
attack_module: model.embed_tokens
formatting_tokens:
  answer_prefix: "### Response:\n"
  answer_suffix: ""
  prompt_prefix: "### Instruction:\n"
  prompt_suffix: "\n"
hf_name: deepseek-ai/deepseek-coder-33b-instruct
attn_implementation: flash_attention_2
load_in_8bit: false
load_in_4bit: false