embedding_dim: 6144
attack_module: model.tok_embeddings
formatting_tokens:
  answer_prefix: "<|im_start|>assistant\n"
  answer_suffix: "<|im_end|>"
  prompt_prefix: "<|im_start|>user\n"
  prompt_suffix: "<|im_end|>\n"
hf_name: internlm/internlm2-chat-20b
attn_implementation: flash_attention_2
load_in_8bit: false
load_in_4bit: false
