embedding_dim: 8192
attack_module: model.embed_tokens
formatting_tokens:
  answer_prefix: ""
  answer_suffix: ""
  prompt_prefix: "[INST] "
  prompt_suffix: " [/INST]"
hf_name: meta-llama/Llama-2-70b-chat-hf
attn_implementation: flash_attention_2
load_in_8bit: false
load_in_4bit: true
