embedding_dim: 7168
attack_module: transformer.wte
formatting_tokens:
  answer_prefix: ""
  answer_suffix: ""
  prompt_prefix: ""
  prompt_suffix: ""
hf_name: mosaicml/mpt-30b-chat
attn_implementation: flash_attention_2
load_in_8bit: false
load_in_4bit: false
