embedding_dim: 6144
attack_module: model.embed_tokens
formatting_tokens:
  answer_prefix: "### Response\n"
  answer_suffix: ""
  prompt_prefix: "### Instruction\n"
  prompt_suffix: "\n\n"
hf_name: bigcode/starcoder2-15b-instruct-v0.1
attn_implementation: flash_attention_2
load_in_8bit: false
load_in_4bit: false
