embedding_dim: 3072
attack_module: model.embed_tokens
formatting_tokens:
  answer_prefix: "<|im_start|>assistant\n"
  answer_suffix: "<|im_end|>"
  prompt_prefix: "<|im_start|>user\n"
  prompt_suffix: "<|im_end|>\n"
hf_name: HuggingFaceH4/zephyr-7b-gemma-v0.1
attn_implementation: flash_attention_2
load_in_8bit: false
load_in_4bit: false
