embedding_dim: 6144
attack_module: model.embed_tokens
formatting_tokens:
  answer_prefix: ""
  answer_suffix: ""
  prompt_prefix: "[INST] "
  prompt_suffix: " [/INST]"
hf_name: HuggingFaceH4/zephyr-orpo-141b-A35b-v0.1
attn_implementation: flash_attention_2
load_in_8bit: false
load_in_4bit: true
